version: 2
updates:
  # Проверка зависимостей Python пакетов
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "andrey-bogush"  # Замените на ваш GitHub username
    target-branch: "main"
    versioning-strategy:
      increase: "all"
      
  # Проверка обновлений для GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci-cd"
      - "dependencies"
    open-pull-requests-limit: 5 